eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false #\u672C\u5730\u6D4B\u8BD5\u7684\u65F6\u5019\u5199false
  client:
    registerWithEureka: false #\u662F\u5426\u5C06\u81EA\u5DF1\u6CE8\u518C\u5230Eureka\u670D\u52A1\u4E2D\uFF0C\u9ED8\u8BA4\u4E3Atrue\uFF0C\u672C\u5730\u6D4B\u8BD5\u7684\u65F6\u5019\u5199false
    fetchRegistry: false #\u662F\u5426\u4ECEEureka\u4E2D\u83B7\u53D6\u6CE8\u518C\u4FE1\u606F\uFF0C\u9ED8\u8BA4\u4E3Atrue
    serviceUrl:
      defaultZone: http://RiverChief:Jugg_26.NdL11@localhost:10143/eureka/

server:
  port: 10030 #\u670D\u52A1\u7AEF\u53E3

spring:
  application:
    name: jenkin-test #\u6307\u5B9A\u670D\u52A1\u540D
